name: Deploy Sanity and Blog

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    working-directory: ./frontend 

jobs:
  deploy-sanity:
    env:
      SANITY_AUTH_TOKEN: "${{ secrets.SANITY_AUTH_TOKEN }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sanity
    
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            sanity

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: |
            sanity/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Deploy Sanity
        run: npm run deploy


  build-blog:
    needs: deploy-sanity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            frontend

      - name: Install, build, and upload your site
        uses: withastro/action@v1
        with:
          path: ./frontend 


  deploy-blog:
    needs: build-blog
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

