name: Deploy Sanity and Website
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  deploy-sanity:
    secrets:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
    uses: ./.github/workflows/deploy-sanity.yml
  deploy-website:
    uses: ./.github/workflows/deploy-website.yml
    needs: [ deploy-sanity ]