name: Deploy Sanity and Website
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-sanity:
    uses: ./.github/workflows/deploy-sanity.yml
  deploy-website:
    uses: ./.github/workflows/deploy-website.yml
    needs: [ deploy-sanity ]